---
name: Code for New Hampshire
markdown: redcarpet
highlighter: pygments
exclude:
- Gemfile
- Gemfile.lock
- README
- Rakefile
- s3_website.yml
sitemap:
  file: /sitemap.xml
  exclude:
  - /robots.txt
  - /feed.xml
url: http://www.codefornh.org
